services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log/nginx/access.log:/var/log/access.log
      - /var/log/mysql/general.log:/var/log/mysql/general.log
      - /var/log/php-fpm/error.log:/var/log/php-fpm/error.log
      - /var/log/mysql/slow.log:/var/log/mysql/slow.log
      - /var/log/mariadb/mariadb.log:/var/log/mariadb/mariadb.log
    networks:
      - opensearch-net
networks:
  opensearch-net:
